### ISSUE TITLE
Unlimited distance 

### ISSUE THREAD

**Issue by FjamZoo** [loljoshie/nui_drawtext#1]
Please put a distance cap, some "trolls" will go onto servers and type in naughty naughty word and have it stick to make all see it 😢

**Comment by FjamZoo** [comment]
Also another suggestion, make log events to qb-logs, and auto bans for bad words which could be configureable? Would add a lot to the experience and get rid of the "trolls" faster

**Comment by loljoshie** [comment]
Just closing this for the main issue of title unlimited distance. That's been fixed the other things you listed I still have saved, thanks!
