### ISSUE TITLE
Suggest to use qb-input

### ISSUE THREAD

**Issue by darknight2590** [loljoshie/nui_drawtext#3]

**Comment by Griefa** [comment]
Out of curiosity, do you know what nui_drawtext does? Because theres no point added another resource for this

**Comment by loljoshie** [comment]
There's no benefit to this suggestion, if anything it would be an extra resource and furthermore to my knowledge qb-input does not implement creation of drawtext nor do they have the customizability features/style. Thanks for the suggestion though!
